function val=model_example(x,y,keyf,keyxy)
 
if nargin<4 || isempty(keyxy)
    switch keyf
    case 'f'; val = [x(1)^2 + x(2)^2*y(2) - 1/3 * y(1)^3];
    case 'F'; val = [x(1) + y(1); ...
                     y(2)];
    case 'G'; val = [x(1)^2 + y(1); ...
                     y(1) * y(2)];    
    case 'G_tilde'; val = [y(1) - 10; ...
                           0 - y(1); ...
                           y(2) - 10; ...
                           0 - y(2)];
    end    
else
    switch keyf
    case 'f'   
        switch keyxy
        case 'x' ; val = [2*x(1), 2*x(2)*y(2)];          
        case 'y' ; val = [-y(1)^2, x(2)^2];   
        case 'xx'; val = [2, 0; ...
                          0, 2*y(2)];
        case 'xy'; val = [0, 0; ...
                          0, 2*x(2)];
        case 'yy'; val = [-2*y(1), 0; ...
                          0,       0];    
        end 
    case 'G'
        switch keyxy
        case 'x' ; val = [2*x(1), 0; ... 
                          0,      0]; 
        case 'y' ; val = [1,    0; ...
                          y(2), y(1)];   
        case 'xx'; val = [2, 0; ...
                          0, 0; ...
                          0, 0; ...
                          0, 0];
        case 'xy'; val = zeros(4, 2);
        case 'yy'; val = [0, 0; ...
                          0, 0; ...
                          0, 1; ...
                          1, 0];
        end                         
    end   
end

end




