function val=paper_example(x,y,keyf,keyxy)
 
if nargin<4 || isempty(keyxy)
    switch keyf
    case 'f'; val = [1/4 * ((x(1) - 2)^2 + (x(2) - 1)^2) + ...
                        1/16 * (x(2)*y + (5 - y)^2) + sin(x(2)/10);  ...
                     1/80 * (x(1)^2 + (x(2)-6)^4 - 2*x(1)*y - (5 - y)^2)];
    case 'F'; val = [x(1) + x(2).^2 + y + sin(x(1) + y); ...
                     cos(x(2)) .* (0.1 + y) .* exp(-x(1)./(0.1 + x(2)))];
    case 'G'; val = [x(1)^2 - x(2); ...
                     5*x(1)^2 + x(2) - 10; ...
                     x(2) - 5 + y/6; ...
                     -x(1)];    
    case 'G_tilde'; val = [y - 10; ...
                           0 - y];
    end    
else
    switch keyf
    case 'f'   
        switch keyxy
        case 'x' ; val = [1/2 * (x(1) - 2), 1/2 * (x(2) - 1) + y/16 + ...
                                            1/10 * cos(x(2)/10); ...
                          1/20 * (x(2) - 6)^3,  1/40 * (x(1) - y)];          
        case 'y' ; val = [1/16 * (x(2) - 2*(5 - y)); ...
                          1/80 * (-2*x(1) + 2*(5 - y))];   
        case 'xx'; val = [1/2, 0; ...
                          0, 1/2 - 1/100 * sin(x(2)/10); ...
                          1/40, 0; ...
                          0, 3/20 * (x(2) - 6)^2];
        case 'xy'; val = [0, 1/16; ...
                          -1/40, 0];
        case 'yy'; val = [1/8; ...
                          -1/40];    
        end         
    case 'G'
        switch keyxy
        case 'x' ; val = [2*x(1), -1; ... 
                          10*x(1), 1; ...
                          0, 1; ...
                          -1, 0]; 
        case 'y' ; val = [0; ...
                          0; ...
                          1/6; ...
                          0];   
        case 'xx'; val = [2, 0; 0, 0; ...
                          10, 0; 0, 0; ... 
                          0, 0; 0, 0; ...
                          0, 0; 0, 0];
        case 'xy'; val = zeros(4, 2);
        case 'yy'; val = zeros(4, 1);    
        end      
    end   
end

end




